descriptor-schema-version: "2.2"

info:
  name: Processing
  description: "Final"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  cpuarch: "x86_64"
  type: docker
  resources:
    profile: c1.small
    network:
      -
        interface-name: eth0
        ports:
          tcp:
            - 5000

  startup:
    rootfs: rootfs.tar
    target: ["python3","/p1.py"]
